<?php

use Illuminate\Filesystem\Filesystem;
use SchenkeIo\PackagingTools\Markdown\MarkdownAssembler;
use SchenkeIo\PackagingTools\Setup\ProjectContext;

it('adds the generated by footer by default', function () {
    $filesystem = Mockery::mock(Filesystem::class);
    $filesystem->shouldReceive('get')->andReturn(json_encode(['name' => 'test/project']));
    $filesystem->shouldReceive('exists')->andReturn(true);
    $filesystem->shouldReceive('isDirectory')->andReturn(true);
    $filesystem->shouldReceive('files')->andReturn([]);

    $footer = "\n\n---\n\nMarkdown file generated by [schenke-io/packaging-tools](https://github.com/schenke-io/packaging-tools)\n";

    $filesystem->shouldReceive('put')->once()->with(Mockery::any(), Mockery::on(function ($content) use ($footer) {
        return str_ends_with($content, $footer);
    }));

    $projectContext = new ProjectContext($filesystem);
    $mda = new MarkdownAssembler('src_dir', $projectContext);

    ob_start();
    $mda->writeMarkdown('output.md');
    ob_get_clean();
});

it('skips the generated by footer when skipWrittenBy() is called', function () {
    $filesystem = Mockery::mock(Filesystem::class);
    $filesystem->shouldReceive('get')->andReturn(json_encode(['name' => 'test/project']));
    $filesystem->shouldReceive('exists')->andReturn(true);
    $filesystem->shouldReceive('isDirectory')->andReturn(true);
    $filesystem->shouldReceive('files')->andReturn([]);

    $footer = 'Markdown file generated by [schenke-io/packaging-tools](https://github.com/schenke-io/packaging-tools)';

    $filesystem->shouldReceive('put')->once()->with(Mockery::any(), Mockery::on(function ($content) use ($footer) {
        return ! str_contains($content, $footer);
    }));

    $projectContext = new ProjectContext($filesystem);
    $mda = new MarkdownAssembler('src_dir', $projectContext);
    $mda->skipWrittenBy();

    ob_start();
    $mda->writeMarkdown('output.md');
    ob_get_clean();
});
